language: generic
compiler: gcc
matrix:
  include:
    - name: 'ros kinetic'
      dist: xenial
      env: ci_ubuntu=xenial ci_ros_distro=kinetic
    - name: 'ros melodic'
      dist: bionic
      env: ci_ubuntu=bionic ci_ros_distro=melodic

branches:
  only:
    - develop

before_install:
  - echo "deb http://packages.ros.org/ros/ubuntu ${CI_UBUNTU} main" | sudo tee -a /etc/apt/sources.list
  - curl http://packages.ros.org/ros.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq dpkg python-catkin-lint python-catkin-tools python-rosdep

install:
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/webrtc
  - rosdep install -q --from-paths /tmp/ws/src --ignore-src --rosdistro ${CI_ROS_DISTRO} -y

before_script:
  - source /opt/ros/${CI_ROS_DISTRO}/setup.bash
  - catkin config -w /tmp/ws --install

script:
  - catkin_lint /tmp/ws/src/webrtc
  - catkin build -w /tmp/ws -p1 -j2 --no-status -i

